package constants

// Key constants for keyboard shortcuts.
const (
	KeyCtrlD         = "ctrl+d"
	KeyEsc           = "esc"
	KeyEnter         = "enter"
	KeyTab           = "tab"
	KeyShiftTab      = "shift+tab"
	KeyUp            = "up"
	KeyDown          = "down"
	KeyLeft          = "left"
	KeyRight         = "right"
	KeyPgUp          = "pgup"
	KeyPgDown        = "pgdown"
	KeyK             = "k"
	KeyJ             = "j"
	KeyH             = "h"
	KeyL             = "l"
	KeyP             = "p"
	KeyD             = "d"
	KeyE             = "e"
	KeyQ             = "q"
	KeyA             = "a"
	KeyV             = "v"
	KeyY             = "y"
	KeyN             = "n"
	KeyX             = "x"
	KeySlash         = "/"
	KeySpace         = "space"
	KeySpaceBar      = " "
	KeyDelete        = "delete"
	KeyCtrlN         = "ctrl+n"
	KeyCtrlP         = "ctrl+p"
	KeyCtrlB         = "ctrl+b"
	KeyCtrlT         = "ctrl+t"
	KeyCtrlR         = "ctrl+r"
	KeyCtrlO         = "ctrl+o"
	KeyCtrlC         = "ctrl+c"
	KeyCtrlX         = "ctrl+x"
	KeyCtrlF         = "ctrl+f"
	KeyShiftUp       = "shift+up"
	KeyShiftDown     = "shift+down"
	KeyCtrlShiftUp   = "ctrl+shift+up"
	KeyCtrlShiftDown = "ctrl+shift+down"
	KeyCtrlShiftS    = "ctrl+shift+s"
	KeyCtrlA         = "ctrl+a"
	KeyCtrlL         = "ctrl+l"
	KeyCtrlS         = "ctrl+s"
	KeyCtrlEnter     = "ctrl+enter"
	KeyCtrlUp        = "ctrl+up"
	KeyCtrlK         = "ctrl+k"
	KeyCtrlDown      = "ctrl+down"
	KeyCtrlJ         = "ctrl+j"
)
