FROM golang:1.24-bookworm
RUN apt-get update && apt-get install -y --no-install-recommends \
    expect asciinema curl git build-essential fonts-dejavu-core \
    && rm -rf /var/lib/apt/lists/*
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y && \
    . /root/.cargo/env && \
    cargo install --git https://github.com/asciinema/agg && \
    rm -rf /root/.cargo/registry /root/.cargo/git
ENV PATH=/root/.cargo/bin:$PATH
WORKDIR /app
COPY . .
RUN go build -o goemqutiti .
ENTRYPOINT ["bash"]
