// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: proxy/proxy.proto

package proxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_proxy_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *WriteRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *WriteRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *WriteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_proxy_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_proxy_proxy_proto_rawDescGZIP(), []int{1}
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_proxy_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *ReadRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *ReadRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ReadRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        [][]byte               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_proxy_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_proxy_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *ReadResponse) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proxy_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *DeleteRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proxy_proxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proxy_proxy_proto_rawDescGZIP(), []int{5}
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proxy_proxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proxy_proto_rawDescGZIP(), []int{6}
}

type DBInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBInfo) Reset() {
	*x = DBInfo{}
	mi := &file_proxy_proxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBInfo) ProtoMessage() {}

func (x *DBInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBInfo.ProtoReflect.Descriptor instead.
func (*DBInfo) Descriptor() ([]byte, []int) {
	return file_proxy_proxy_proto_rawDescGZIP(), []int{7}
}

func (x *DBInfo) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *DBInfo) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *DBInfo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dbs           []*DBInfo              `protobuf:"bytes,1,rep,name=dbs,proto3" json:"dbs,omitempty"`
	Reads         uint64                 `protobuf:"varint,2,opt,name=reads,proto3" json:"reads,omitempty"`
	Writes        uint64                 `protobuf:"varint,3,opt,name=writes,proto3" json:"writes,omitempty"`
	Deletes       uint64                 `protobuf:"varint,4,opt,name=deletes,proto3" json:"deletes,omitempty"`
	Clients       int64                  `protobuf:"varint,5,opt,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proxy_proxy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proxy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proxy_proxy_proto_rawDescGZIP(), []int{8}
}

func (x *StatusResponse) GetDbs() []*DBInfo {
	if x != nil {
		return x.Dbs
	}
	return nil
}

func (x *StatusResponse) GetReads() uint64 {
	if x != nil {
		return x.Reads
	}
	return 0
}

func (x *StatusResponse) GetWrites() uint64 {
	if x != nil {
		return x.Writes
	}
	return 0
}

func (x *StatusResponse) GetDeletes() uint64 {
	if x != nil {
		return x.Deletes
	}
	return 0
}

func (x *StatusResponse) GetClients() int64 {
	if x != nil {
		return x.Clients
	}
	return 0
}

var File_proxy_proxy_proto protoreflect.FileDescriptor

const file_proxy_proxy_proto_rawDesc = "" +
	"\n" +
	"\x11proxy/proxy.proto\x12\x05proxy\"h\n" +
	"\fWriteRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\"\x0f\n" +
	"\rWriteResponse\"Q\n" +
	"\vReadRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\"&\n" +
	"\fReadResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\"S\n" +
	"\rDeleteRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\"\x10\n" +
	"\x0eDeleteResponse\"\x0f\n" +
	"\rStatusRequest\"N\n" +
	"\x06DBInfo\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\"\x93\x01\n" +
	"\x0eStatusResponse\x12\x1f\n" +
	"\x03dbs\x18\x01 \x03(\v2\r.proxy.DBInfoR\x03dbs\x12\x14\n" +
	"\x05reads\x18\x02 \x01(\x04R\x05reads\x12\x16\n" +
	"\x06writes\x18\x03 \x01(\x04R\x06writes\x12\x18\n" +
	"\adeletes\x18\x04 \x01(\x04R\adeletes\x12\x18\n" +
	"\aclients\x18\x05 \x01(\x03R\aclients2\xdc\x01\n" +
	"\aDBProxy\x122\n" +
	"\x05Write\x12\x13.proxy.WriteRequest\x1a\x14.proxy.WriteResponse\x12/\n" +
	"\x04Read\x12\x12.proxy.ReadRequest\x1a\x13.proxy.ReadResponse\x125\n" +
	"\x06Delete\x12\x14.proxy.DeleteRequest\x1a\x15.proxy.DeleteResponse\x125\n" +
	"\x06Status\x12\x14.proxy.StatusRequest\x1a\x15.proxy.StatusResponseB(Z&github.com/marang/emqutiti/proxy;proxyb\x06proto3"

var (
	file_proxy_proxy_proto_rawDescOnce sync.Once
	file_proxy_proxy_proto_rawDescData []byte
)

func file_proxy_proxy_proto_rawDescGZIP() []byte {
	file_proxy_proxy_proto_rawDescOnce.Do(func() {
		file_proxy_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_proxy_proto_rawDesc), len(file_proxy_proxy_proto_rawDesc)))
	})
	return file_proxy_proxy_proto_rawDescData
}

var file_proxy_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proxy_proxy_proto_goTypes = []any{
	(*WriteRequest)(nil),   // 0: proxy.WriteRequest
	(*WriteResponse)(nil),  // 1: proxy.WriteResponse
	(*ReadRequest)(nil),    // 2: proxy.ReadRequest
	(*ReadResponse)(nil),   // 3: proxy.ReadResponse
	(*DeleteRequest)(nil),  // 4: proxy.DeleteRequest
	(*DeleteResponse)(nil), // 5: proxy.DeleteResponse
	(*StatusRequest)(nil),  // 6: proxy.StatusRequest
	(*DBInfo)(nil),         // 7: proxy.DBInfo
	(*StatusResponse)(nil), // 8: proxy.StatusResponse
}
var file_proxy_proxy_proto_depIdxs = []int32{
	7, // 0: proxy.StatusResponse.dbs:type_name -> proxy.DBInfo
	0, // 1: proxy.DBProxy.Write:input_type -> proxy.WriteRequest
	2, // 2: proxy.DBProxy.Read:input_type -> proxy.ReadRequest
	4, // 3: proxy.DBProxy.Delete:input_type -> proxy.DeleteRequest
	6, // 4: proxy.DBProxy.Status:input_type -> proxy.StatusRequest
	1, // 5: proxy.DBProxy.Write:output_type -> proxy.WriteResponse
	3, // 6: proxy.DBProxy.Read:output_type -> proxy.ReadResponse
	5, // 7: proxy.DBProxy.Delete:output_type -> proxy.DeleteResponse
	8, // 8: proxy.DBProxy.Status:output_type -> proxy.StatusResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proxy_proxy_proto_init() }
func file_proxy_proxy_proto_init() {
	if File_proxy_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_proxy_proto_rawDesc), len(file_proxy_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proxy_proxy_proto_goTypes,
		DependencyIndexes: file_proxy_proxy_proto_depIdxs,
		MessageInfos:      file_proxy_proxy_proto_msgTypes,
	}.Build()
	File_proxy_proxy_proto = out.File
	file_proxy_proxy_proto_goTypes = nil
	file_proxy_proxy_proto_depIdxs = nil
}
